//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class layout extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JTextField jcomp4;
    private JTextField jcomp5;
    private JPasswordField jcomp6;
    private JButton jcomp7;
    private JButton jcomp8;
    private JButton jcomp9;
    private JButton jcomp10;

    public layout() {
        //construct components
        jcomp1 = new JLabel ("Nome:");
        jcomp2 = new JLabel ("Sobrenome:");
        jcomp3 = new JLabel ("CPF:");
        jcomp4 = new JTextField (5);
        jcomp5 = new JTextField (5);
        jcomp6 = new JPasswordField (5);
        jcomp7 = new JButton ("Incluir");
        jcomp8 = new JButton ("Atualizar");
        jcomp9 = new JButton ("Listar");
        jcomp10 = new JButton ("Excluir");

        //set components properties
        jcomp1.setToolTipText (" 	- Valida Movimento  Todas herdam de peça  Divide a posição por 8: resultado é a linha e o resto a coluna.");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 367));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (10, 10, 100, 25);
        jcomp2.setBounds (10, 40, 100, 25);
        jcomp3.setBounds (10, 75, 100, 25);
        jcomp4.setBounds (95, 10, 540, 25);
        jcomp5.setBounds (95, 40, 540, 25);
        jcomp6.setBounds (95, 70, 540, 25);
        jcomp7.setBounds (280, 115, 85, 25);
        jcomp8.setBounds (370, 115, 85, 25);
        jcomp9.setBounds (460, 115, 85, 25);
        jcomp10.setBounds (550, 115, 85, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("layout");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new layout());
        frame.pack();
        frame.setVisible (true);
    }
}
